### ISSUE TITLE
Do we have support for .Net vNext developer's yet?

### ISSUE THREAD

**Issue by rave1502** [daishisystems/Daishi.Armor.WebFramework#2]
I am trying to implement ARMOR.WebFrametowk on plain Web API project. This project template do not have global.asx for webconfigsys.cs file by default, I am not sure where I can add "config.Filters.Add(new WebApiArmorFortifyFilter());" in mycode.

**Comment by rave1502** [comment]
> The plain Web API do not have global.asx for webconfigsys.cs file by default, I am not sure where I can add "config.Filters.Add(new WebApiArmorFortifyFilter());" in mycode.

**Comment by daishisystems** [comment]
You can adds global.asax file manually:
http://stackoverflow.com/questions/26535924/global-asax-file-is-missing-on-my-asp-net-empty-web-application-project

On Friday, 31 July 2015, rave1502 notifications@github.com wrote:

> The plain Web API do not have global.asx for webconfigsys.cs file by
> default, I am not sure where I can add "config.Filters.Add(new
> WebApiArmorFortifyFilter());" in mycode.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/daishisystems/Daishi.Armor.WebFramework/issues/2.

## 

_Paul Mooney_
_Technology Consultant_
- http://www.insidethecpu.com*
- http://insidethecpu.com/feed/ https://github.com/daishisystems**
  https://twitter.com/daishisystems**
  https://www.linkedin.com/in/daishisystems**
  https://www.youtube.com/user/daishisystems**
  https://plus.google.com/u/0/102806071104797194504/posts*
